Feature/Update Repo command
atlassian-api/atlassian-python-api pull request #643
Opened 2020-12-08 02:22 UTC by timsavage

The Update repo command is missing allowing for updates to repository description.

The change covers both code and docs, and all tox checks pass.

2020-12-08 16:47 UTC, Spacetown requested changes

2020-12-08 16:47 UTC, Spacetown commented on atlassian/bitbucket/__init__.py
> +        data = self.get_repo(project_key, repository_slug)
The get isn't needed becore the put because missing Keys in the put aren't changed.

2020-12-08 22:03 UTC, timsavage commented
That is what I would expect from a put, however that was the pattern used
in the put request to update a project.

Will make the update.

Cheers

On Wed, 9 Dec 2020, 03:47 Michael Förderer, <notifications@github.com>
wrote:

> *@Spacetown* requested changes on this pull request.
> ------------------------------
>
> In atlassian/bitbucket/__init__.py
> <https://github.com/atlassian-api/atlassian-python-api/pull/643#discussion_r538588121>
> :
>
> > @@ -682,6 +682,23 @@ def get_repo(self, project_key, repository_slug):
>          url = self._url_repo(project_key, repository_slug)
>          return self.get(url)
>
> +    def update_repo(self, project_key, repository_slug, **params):
> +        """
> +        Update a repository in a project. This operates based on slug not name which may
> +        be confusing to some users.
> +        :param project_key: Key of the project you wish to look in.
> +        :param repository_slug: url-compatible repository identifier
> +        :return: None if the repo does not exist, else the value of the put request.
> +        """
> +        data = self.get_repo(project_key, repository_slug)
>
> The get isn't needed becore the put because missing Keys in the put aren't
> changed.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/atlassian-api/atlassian-python-api/pull/643#pullrequestreview-547423446>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AABRX4Y2LYX5VMKAUOSGTE3STZKB5ANCNFSM4URJ3UWQ>
> .
>

2020-12-10 20:56 UTC, Spacetown commented
@timsavage I was wondering when implementing the OO interface and checked it with BB cloud. It is working without the GEt.

2020-12-11 02:58 UTC, timsavage commented
Done, the update_project method now matches.

2020-12-17 04:05 UTC, merged