Add URL encoding for multiple GET parameters
atlassian-api/atlassian-python-api pull request #645
Opened 2020-12-10 08:26 UTC by dim0x69

Disclaimer: I only looked at Jira until now :)

Currently there seems not to be a method which adds multiple GET parameters to the API request. Indeed, these might happen in the future (I will add another Pull Request  to add the "expand" keyword to Jira.issue_field_value() and Jira.issue() ;) )

This Pull Request adds the option to have multiple GET parameters in the URL.

2020-12-10 20:48 UTC, Spacetown requested changes

2020-12-10 20:48 UTC, Spacetown commented on atlassian/rest_client.py
> +        else:
This should be:
``python
elsif params_already_in_url:
```
At the moment the `&`i s added even if tere are no `parmas`and no `flags`.

2020-12-11 12:43 UTC, Spacetown commented on atlassian/rest_client.py
> +        else:
Ok. Instead of the branch I selected the first commit.

2020-12-14 09:44 UTC, dim0x69 commented
Hi @Spacetown ,

Thanks for your suggestions! On first sight I (logically) don't see a difference in our codes, but yours is nicer to read :) 
I updated the Pull Request with  0fcc4d7 to include your idea.

2020-12-14 19:23 UTC, Spacetown commented
> Hi @Spacetown ,
> 
> Thanks for your suggestions! On first sight I (logically) don't see a difference in our codes, but yours is nicer to read :)
> I updated the Pull Request with [0fcc4d7](https://github.com/atlassian-api/atlassian-python-api/commit/0fcc4d7ee78fa907be5835015da9f87b2547dd30) to include your idea.

I've checked again and you're right, it was ok. But I think, now it's easier to read.

2020-12-15 09:47 UTC, dim0x69 commented
I updated the PR with black formatting @Spacetown

2020-12-17 04:02 UTC, merged

2020-12-17 04:02 UTC, gonchik commented
Thank you both for the improvement!