Bitbucket Cloud: allow to access repositories directly
atlassian-api/atlassian-python-api pull request #923
Opened 2022-01-14 17:34 UTC by flichtenheld

This allows to access a Repository object without having
access to the workspace endpoint.

Signed-off-by: Frank Lichtenheld <frank@lichtenheld.com>

2022-04-28 19:42 UTC, Spacetown requested changes

2022-08-23 08:44 UTC, gonchik commented
@flichtenheld does it actual ?

2022-08-24 12:05 UTC, flichtenheld commented
> @flichtenheld does it actual ?

Sorry, I don't understand. What is the question?

2022-08-24 12:08 UTC, flichtenheld commented on atlassian/bitbucket/cloud/repositories/__init__.py
> +        return self._get_object(super(Repositories, self).get("{}/{}".format(workspace, workspace)))
After the changes it is now broken:

```suggestion
        return self._get_object(super(Repositories, self).get("{}/{}".format(workspace, repo_slug)))
```

2022-09-11 07:28 UTC, merged